/*
 * This source file was generated by the Gradle 'init' task
 */
package com.infinitehorizons.scaffold.microservices;

import com.infinitehorizons.scaffold.microservices.extension.ScaffoldMicroservicesExtension;
import org.gradle.api.Project;
import org.gradle.api.Plugin;
import org.jetbrains.annotations.NotNull;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ScaffoldMicroservicesPlugin implements Plugin<@NotNull Project> {
    private static final Logger log = LoggerFactory.getLogger(ScaffoldMicroservicesPlugin.class);

    @Override
    public void apply(@NotNull Project project) {
        ScaffoldMicroservicesExtension extension = project.getExtensions()
                .create("scaffoldMicroServices", ScaffoldMicroservicesExtension.class);

        project.getTasks().register("scaffoldInfo", task -> {
            task.setGroup("Infinite Horizons");
            task.setDescription("Verifica la configuración del plugin.");

            task.doLast(t -> {
                log.info("==========================================");
                log.info("   Infinite Horizons - Scaffolding System ");
                log.info("==========================================");
                log.info("   Empresa:  " + extension.getCompanyName());
                log.info("   Proyecto: " + extension.getProjectName());
                log.info("   Paquete:  " + extension.getPackageName());
                log.info("==========================================");
            });
        });
    }
}
